### ISSUE TITLE
pgbackrest-toggle-archiving is not idempotent

### ISSUE THREAD

**Issue by mbanck** [credativ/elephant-shed#17]
AFAICT, `systemctl start pgbackrest-toggle-archiving@<cluster-name>` turn archiving on or off, depending on the previous state.

That makes it really difficult to handle with Ansible, as running something like

```
 name: Enable pgBackrest full backup timer
  systemd:
    name: pgbackrest@{{ postgresql_cluster }}.timer
    state: started
```

Will turn archiving on or off for each run, making the Ansible runs non-idempotent.

Is there a way to circumvent that? Conceptually, running `systemctl enable/disable pgbackrest-archiving@<cluster-name>' would be the best from a UX perspective, but systemd won't invoke the `/usr/share/elephant-shed/pgbackrest-toggle-archiving` script but bail out.
